//Universal Types
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//Exercise creator Types
export const SET_EXERCISE_FROM_SCHEMA = "SET_EXERCISE_FROM_SCHEMA";
export const SET_CURRENT_SCHEMA = "SET_CURRENT_SCHEMA";
export const SET_EXERCISE_NAME = "SET_EXERCISE_NAME";
export const SET_EXERCISE_TOP = "SET_EXERCISE_TOP";
export const CHANGE_EXERCISE_LEFT = "CHANGE_EXERCISE_LEFT";
export const CHANGE_EXERCISE_RIGHT = "CHANGE_EXERCISE_RIGHT";
export const CLEAR_CURRENT_SCHEMA = "CLEAR_CURRENT_SCHEMA";
export const CLEAR_CURRENT_EXERCISE = "CLEAR_CURRENT_EXERCISE";
export const GET_SCHEMAS_FROM_API = "GET_SCHEMAS_FROM_API";

//Schema creator Types
export const SET_SCHEMA_NAME = "SET_SCHEMA_NAME";
export const SET_SCHEMA_LEFT = "SET_SCHEMA_LEFT";
export const SET_SCHEMA_RIGHT = "SET_SCHEMA_RIGHT";
export const SET_SCHEMA_TOP = "SET_SCHEMA_TOP";
export const SET_SCHEMA_ERROR = "SET_SCHEMA_TOP";
export const CLEAR_SCHEMA_ERROR = "SET_SCHEMA_TOP";
export const POST_SCHEMA_TO_API = "POST_SCHEMA_TO_API";

//Exercise test types
export const SET_CURRENT_SCHEMA_FROM_API = "SET_SCHEMA_FROM_API";
export const SET_CURRENT_TEST_EXERCISE = "SET_CURRENT_TEST_EXERCISE";
export const GET_EXERCISE_FROM_API = "GET_EXERCISE_FROM_API";
